### ISSUE TITLE
Windows Phone 8 compilation error

### ISSUE THREAD

**Issue by hegdehk1** [nicolaspanel/libsvm.net#16]
I am trying to use this libSVM in my windows phone 8 code, but I am not able to do so. I followed the instructions to install your implementation and the dependencies, but I get this error:

Cannot resolve Assembly or Windows Metadata file 'IKVM.OpenJDK.Security.dll'    C:\Users\nagaraj\Desktop\junk\CSW\File access sample\C#\WindowsPhone\FileAccess.WindowsPhone.csproj FileAccess.WindowsPhone

I am attaching the exact error I am getting. 
![wp8cserror](https://cloud.githubusercontent.com/assets/4642949/5331555/9ee18c76-7df5-11e4-8296-52cbdf920f41.PNG)

Please help me !

Thanks so much!

**Comment by laxmanrizecorp** [comment]
Hi gsssrao, 

Can you please let us know, how to  resolve this issue in windows phone. I am new to development on windows phone.

Thanks,.

**Comment by nicolaspanel** [comment]
like @gsssrao said, some dependencies of this project are not in WP .NET framework.

Making this lib compatible with WP is not possible right now since I have no experience/device with Windows Phone.

If anyone is interested to do so, I would be glad to give him privileged access to this repo.

BR

**Comment by gsssrao** [comment]
@laxmanrizecorp as I had said earlier, I was unable to resolve this issue because Windows Phone does not support the whole of the .NET framework. 

For my work I just wanted to run SVM on Windows Phone. So, I tried to find an alternative to libsvm which works on Windows Phone. I found out that Accord.NET had a fork which works well with Windows Phone. You can find it [here](https://github.com/cureos/accord). The documentation can be found [here](https://github.com/accord-net/framework/wiki/Classification). I also had to install [CSS Shim](https://www.nuget.org/packages/shim) and [Microsoft Compression Build](https://www.nuget.org/packages/Microsoft.Bcl.Compression) to run this. This was for ```2.14.0-pre1``` release.

This was about a year ago, I don't know whether some other better alternative is there or not.

@nicolaspanel Have you seen Microsoft's [Project Astoria](https://dev.windows.com/en-us/bridges/android)? With this Android version of libsvm should probably run on Windows phone.

**Comment by laxmanrizecorp** [comment]
Hi Gssrao,

I am using the IKVM and using the android code and generate the .dll file and using this script in windows phone development. I got the issue like this

A first chance exception of type 'System.TypeInitializationException' occurred in IKVM.OpenJDK.Core.DLL

Additional information: The type initializer for 'java.lang.String' threw an exception.

I added Accord.NET dll files still it showing same issue. So can you please let us know how I can use Accord.NET dll files in the above issue.

I attached the exact issue image here. please check it and let me know.

Thanks,
Lakshman kumar.M
![windows issue](https://cloud.githubusercontent.com/assets/4851015/10841537/1a9e7e16-7f10-11e5-91f2-4f2b1dc5eb5b.png)

**Comment by gsssrao** [comment]
@laxmanrizecorp Why are you using IKVM and android code?

To use Accord .NET just include the corresponding dll files(in my case they were ```Accord.dll, Acoord.Math.dll, Acoord.IO.dll, Acoord.MachineLearning.dll```. This was for ```2.14.0-pre1``` release.), packages(```CSS Shim``` and ```Bcl Compression``` using Nuget package manager) and run the code as per the examples provided in the documentation.

**Comment by laxmanrizecorp** [comment]
Hi Gssrao,

I am purely android background. So i developed one app in Android framewwork. I want to use same files in windows app development. I used same files in IOS using "j2objc". So same thing is have to develop windows 8 apps using the java code(android). 
In the J2objc is convert whole java files into Objective-c. So we can use same files in IOS development.

I am using the IKVM to try the same thing, I got the above issue.
So can you please suggest,  How to convert whole android code into windows. I am looking your suggested ACCord and windows bridge. But I am not fully aware on windows development. Tell me some sample example how to convert those andorid files in windows development.

Thanks,
Lakshman kumar.M

**Comment by gsssrao** [comment]
Sorry, I have never used the Android Bridge so I can't help you there. But maybe an apk can be installed on a windows phone as per this [link](http://www.ibtimes.co.uk/how-install-android-apk-windows-10-mobile-1514674). There are several other similar links online.
